services:
  myarabic.webapi:
    image: myarabic.webapi
    build:
      context: ./MyArabic.WebApi/
      dockerfile: ../Dockerfile
    environment:
      - "CONNECTIONSTRINGS:DEFAULTCONNECTION=Host=${DB_HOST};Port=5432;Database=${DB_DATABASE};Username=${DB_USER};Password=${DB_PASSWORD}"

